In [1]:
from dfs import DFS
import numpy as np

In [2]:
test = np.array([[0,0,1], [1, 0, 0], [1, 1, 0]])
row, col = 0, 0

In [3]:
test[0, 1]

0

In [4]:
a = DFS(row, col, test)

In [5]:
a.iteration()

In [ ]:
test

array([[0, 0, 1],
       [1, 0, 0],
       [1, 1, 0]])

In [21]:
while a.linked_lst != None:
    print(a.linked_lst.row, a.linked_lst.col)
    a.linked_lst = a.linked_lst.prev

2 2
2 1
1 1
1 0
0 0


In [8]:
a.linked_lst.next

In [3]:
import numpy as np 
#test = np.ones([[0,0,0], [1, 1, 0], [0, 0, 0]])
row, col = 0, 0

In [1]:
class LinkedList:
    def __init__(self, col: int, row: int, next = None, prev=None):
        self.col = col
        self.row = row
        self.next = next
        self.prev = prev

In [70]:
import numpy as np 
test = np.array([[0,0,0], [1, 1, 0], [0, 0, 0]])
vec = np.zeros(test.shape)
vec[0,0] = True
row, col = 0, 0

def generate(x: int, y: int, diff_level:np.double):
    test = np.zeros((x, y))
    for l in range(0, x):
        for m in range(0, y):
            if np.random.uniform() > diff_level:
                test[l, m] = 0
            else:
                test[l, m] = 1
    return test

def dfs(arr, row, col, vec, linkedlist: LinkedList):

    if row < len(arr) - 1 and arr[row + 1, col] == 0 and vec[row + 1, col] == False :
        row = row + 1
        vec[row, col] = True
        temp = linkedlist
        linkedlist.next = LinkedList(row, col)
        linkedlist = linkedlist.next
        #linkedlist.prev = temp
        dfs(arr, row, col, vec, linkedlist)

    elif row > 0 and arr[row - 1, col] == 0 and vec[row - 1, col] == False:
        row = row - 1
        vec[row, col] = True
        temp = linkedlist
        linkedlist.next = LinkedList(row, col)
        linkedlist = linkedlist.next
        #linkedlist.prev = temp
        dfs(arr, row, col, vec, linkedlist)

    elif col < len(arr) - 1 and arr[row, col + 1] == 0 and vec[row, col + 1] == False:
        col = col + 1
        vec[row, col] = True
        temp = linkedlist
        linkedlist.next = LinkedList(row, col)
        linkedlist = linkedlist.next
        #linkedlist.prev = temp
        dfs(arr, row, col, vec, linkedlist)

    elif col > 0  and arr[row, col - 1] == 0 and vec[row, col - 1] == False:
        col = col - 1
        vec[row, col] = True
        temp = linkedlist
        linkedlist.next = LinkedList(row, col)
        linkedlist = linkedlist.next
        #linkedlist.prev = temp
        dfs(arr, row, col, vec, linkedlist)

    else:
        print(linkedlist.row, linkedlist.col)
        if linkedlist.row == 4 and linkedlist.col == 4:
            return True

        else:
            return False


In [71]:
m = np.array([[0, 1, 0, 0], [0, 1, 0, 0], [0, 1, 0, 1], [0, 0, 1, 0]])#generate(5, 5, 0.10)

In [72]:
m

array([[0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 1],
       [0, 0, 1, 0]])

In [73]:
vec = np.zeros((5, 5))

In [74]:
head = Linkedl = LinkedList(0, 0)
dfs(m, 0, 0, vec, Linkedl)

1 3


In [75]:
vec

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [76]:
m

array([[0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 1],
       [0, 0, 1, 0]])

In [77]:
while head.next != None:
    print(head.row, head.col)
    head = head.next
print(head.row, head.col)    

0 0
0 1
0 2
0 3
1 3


In [78]:
vec

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [87]:
np.random.uniform()

0.2779549814756237

In [28]:
np.random.randint(0, 120)

7

In [29]:
head = Linkedl = LinkedList(0, 0)
dfs(test, 0, 0, vec, Linkedl)

0 2


In [45]:
dfs(test, 0, 0, vec, Linkedl)

0 0


False

In [8]:
dfs(test, 0, 0, vec, LinkedList(0, 0))

False

In [71]:
while head.next != None:
    print(head.row, head.col)
    head = head.next

0 0
1 0
2 0
2 1
2 2
1 2


In [18]:
head.col

2

In [9]:
col

0

In [9]:
test[0,0] = 'ada'

ValueError: invalid literal for int() with base 10: 'ada'

In [15]:
test

[[0, 0, 0], [1, 1, 0], [0, 0, 0]]

In [14]:
test = [[0,0,0], [1, 1, 0], [0, 0, 0]]


In [16]:
test[1][0] == True

True

In [20]:
test

[[0, 0, 0], [1, 1, 0], [0, 0, 0]]

In [21]:
1 == True

True